#!/usr/bin/python3
import argparse
import json
import logging
import sys

from avi.sdk.avi_api import ApiSession
from avi.sdk.utils.api_utils import ApiUtils
from avi.sdk.samples.common import get_sample_ssl_params
from requests.packages import urllib3

logger = logging.getLogger(__name__)
ch = logging.StreamHandler(sys.stdout)
root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)
root_logger.addHandler(ch)

urllib3.disable_warnings()


class AviLicenses(object):

    def __init__(self, api):
        self.api = api
        self.api_utils = ApiUtils(api)

    def GetLicenses(self,ctrl):
        resp = self.api.get('licensing/ledger/details')
        if resp.status_code in range(200, 299):
            logger.info(ctrl+': License Info retrieved successfully')
        else:
            logger.info(ctrl+': Error when getting license info : %s' % resp.text)
        return resp.json()



if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('-u', '--user', help='controller user', default='admin')
    parser.add_argument('-p', '--password', help='controller user password', default='avi123')
    parser.add_argument('-c', '--controller', nargs='+', help='controller ip', required=True)

    args = parser.parse_args()    
    ctrl_data = {}
    for ctrl in args.controller:
        api = ApiSession.get_session(ctrl, args.user, args.password, api_version="21.1.3")
        avicontroller = AviLicenses(api)
        lic = AviLicenses.GetLicenses(avicontroller,ctrl)
        ctrl_data[ctrl] = {
            "Available": lic["tier_usages"][0]["usage"]["available"],
            "Consumed": lic["tier_usages"][0]["usage"]["consumed"],
            "Remaining": lic["tier_usages"][0]["usage"]["remaining"]
        }

    #Count Totals
    avail=0
    consumed=0
    remaining=0
    for ctrl in ctrl_data:
        avail=avail+ctrl_data[ctrl]["Available"]
        consumed=consumed+ctrl_data[ctrl]["Consumed"]
        remaining=remaining+ctrl_data[ctrl]["Remaining"]
    ctrl_data["Total"] = {
        "Available": avail,
        "Consumed": consumed,
        "Remaining": remaining
    }
    print(json.dumps(ctrl_data, indent=4, sort_keys=True))



# To use this file:
# python3 license_count_from_controller.py -u 'admin' -p 'Avipassword1' -c 10.10.10.10 10.10.10.11 10.10.10.12
